In [3]:
import pandas as pd

In [4]:
file_path = "./resource/holding.csv"
df = pd.read_csv(file_path)
df

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
0,2998623,2020/11/30,1,2021/01/08,2.55,7078982.0,3.103426e+08,GENERAL MOTORS CO,37045V10
1,2998623,2020/11/30,2,2021/01/08,1.98,3087680.0,2.412404e+08,COGNIZANT TECHNOLOGY SOLS CORP,19244610
2,2998623,2020/11/30,3,2021/01/08,1.89,3714760.0,2.296836e+08,MORGAN STANLEY DEAN WITTER & CO,61744644
3,2998623,2020/11/30,4,2021/01/08,1.75,2815186.0,2.132503e+08,PHILIP MORRIS INTERNATIONAL INC,71817210
4,2998623,2020/11/30,5,2021/01/08,1.65,5248941.0,2.011394e+08,CORTEVA INC,22052L10
...,...,...,...,...,...,...,...,...,...
32878713,3157350,2021/11/30,428,2021/12/21,0.11,25000.0,2.229475e+04,Bausch Health Companies Inc 5% 30-JAN-2028,071734AH
32878714,3157350,2021/11/30,429,2021/12/21,0.11,25000.0,2.148050e+04,Bausch Health Companies Inc 5.25% 30-JAN-2030,071734AJ
32878715,3157350,2021/11/30,429,2021/12/21,0.11,25000.0,2.148400e+04,Bausch Health Companies Inc 5% 15-FEB-2029,071734AM
32878716,3157350,2021/11/30,431,2021/12/21,0.10,25000.0,1.918738e+04,Endo DAC 6% 30-JUN-2028,29273DAC
32878717,3157350,2021/11/30,432,2021/12/21,0.08,25000.0,1.497188e+04,PBF Holding Company LLC 6% 15-FEB-2028,69318FAJ

In [5]:
df.head()

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
0,2998623,2020/11/30,1,2021/01/08,2.55,7078982.0,3.103426e+08,GENERAL MOTORS CO,37045V10
1,2998623,2020/11/30,2,2021/01/08,1.98,3087680.0,2.412404e+08,COGNIZANT TECHNOLOGY SOLS CORP,19244610
2,2998623,2020/11/30,3,2021/01/08,1.89,3714760.0,2.296836e+08,MORGAN STANLEY DEAN WITTER & CO,61744644
3,2998623,2020/11/30,4,2021/01/08,1.75,2815186.0,2.132503e+08,PHILIP MORRIS INTERNATIONAL INC,71817210
4,2998623,2020/11/30,5,2021/01/08,1.65,5248941.0,2.011394e+08,CORTEVA INC,22052L10

In [6]:
df.head(10)

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
0,2998623,2020/11/30,1,2021/01/08,2.55,7078982.0,3.103426e+08,GENERAL MOTORS CO,37045V10
1,2998623,2020/11/30,2,2021/01/08,1.98,3087680.0,2.412404e+08,COGNIZANT TECHNOLOGY SOLS CORP,19244610
2,2998623,2020/11/30,3,2021/01/08,1.89,3714760.0,2.296836e+08,MORGAN STANLEY DEAN WITTER & CO,61744644
3,2998623,2020/11/30,4,2021/01/08,1.75,2815186.0,2.132503e+08,PHILIP MORRIS INTERNATIONAL INC,71817210
4,2998623,2020/11/30,5,2021/01/08,1.65,5248941.0,2.011394e+08,CORTEVA INC,22052L10
5,2998623,2020/11/30,6,2021/01/08,1.64,866386.0,1.997713e+08,GOLDMAN SACHS GROUP INC,38141G10
6,2998623,2020/11/30,7,2021/01/08,1.63,2194727.0,1.976352e+08,C S X CORP,12640810
7,2998623,2020/11/30,8,2021/01/08,1.60,5045923.0,1.939653e+08,AMERICAN INTERNATIONAL GROUP INC,02687478
8,2998623,2020/11/30,9,2021/01/08,1.59,1403360.0,1.937619e+08,P N C FINANCIAL SERVICES GRP INC,69347510
9,2998623,2020/11/30,10,2021/01/08,1.54,3065766.0,1.874409e+08,C B R E GROUP INC,12504L10

In [7]:
df.tail()

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
32878713,3157350,2021/11/30,428,2021/12/21,0.11,25000.0,22294.75,Bausch Health Companies Inc 5% 30-JAN-2028,071734AH
32878714,3157350,2021/11/30,429,2021/12/21,0.11,25000.0,21480.50,Bausch Health Companies Inc 5.25% 30-JAN-2030,071734AJ
32878715,3157350,2021/11/30,429,2021/12/21,0.11,25000.0,21484.00,Bausch Health Companies Inc 5% 15-FEB-2029,071734AM
32878716,3157350,2021/11/30,431,2021/12/21,0.10,25000.0,19187.38,Endo DAC 6% 30-JUN-2028,29273DAC
32878717,3157350,2021/11/30,432,2021/12/21,0.08,25000.0,14971.88,PBF Holding Company LLC 6% 15-FEB-2028,69318FAJ

In [8]:
df.tail(10)

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
32878708,3157350,2021/11/30,423,2021/12/21,0.12,25000.0,22810.50,Staples Inc 10.75% 15-APR-2027,855030AP
32878709,3157350,2021/11/30,424,2021/12/21,0.12,25000.0,22726.50,Sinclair Television Group Inc 4.125% 01-DEC-2030,829259BA
32878710,3157350,2021/11/30,425,2021/12/21,0.12,25000.0,22700.00,Bausch Health Companies Inc 6.25% 15-FEB-2029,071734AK
32878711,3157350,2021/11/30,426,2021/12/21,0.11,25000.0,22685.13,Sinclair Television Group Inc 5.5% 01-MAR-2030,829259AY
32878712,3157350,2021/11/30,427,2021/12/21,0.11,25000.0,22561.75,Service Properties Trust 4.375% 15-FEB-2030,44106MAY
32878713,3157350,2021/11/30,428,2021/12/21,0.11,25000.0,22294.75,Bausch Health Companies Inc 5% 30-JAN-2028,071734AH
32878714,3157350,2021/11/30,429,2021/12/21,0.11,25000.0,21480.50,Bausch Health Companies Inc 5.25% 30-JAN-2030,071734AJ
32878715,3157350,2021/11/30,429,2021/12/21,0.11,25000.0,21484.00,Bausch Health Companies Inc 5% 15-FEB-2029,071734AM
32878716,3157350,2021/11/30,431,2021/12/21,0.10,25000.0,19187.38,Endo DAC 6% 30-JUN-2028,29273DAC
32878717,3157350,2021/11/30,432,2021/12/21,0.08,25000.0,14971.88,PBF Holding Company LLC 6% 15-FEB-2028,69318FAJ

In [9]:
df[444:449]

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
444,2998809,2020/11/30,17,2021/01/08,1.96,1542737.0,39154665.06,EQUITABLE HOLDINGS INC,29452E10
445,2998809,2020/11/30,18,2021/01/08,1.88,1883515.0,37632629.70,CARNIVAL CORP,14365830
446,2998809,2020/11/30,19,2021/01/08,1.80,260036.0,35903170.52,P N C FINANCIAL SERVICES GRP INC,69347510
447,2998809,2020/11/30,20,2021/01/08,1.74,150444.0,34778139.48,CUMMINS INC,23102110
448,2998809,2020/11/30,21,2021/01/08,1.71,725931.0,34278461.82,LINCOLN NATIONAL CORP,53418710

In [10]:
df.loc[[444,446]]

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
444,2998809,2020/11/30,17,2021/01/08,1.96,1542737.0,39154665.06,EQUITABLE HOLDINGS INC,29452E10
446,2998809,2020/11/30,19,2021/01/08,1.80,260036.0,35903170.52,P N C FINANCIAL SERVICES GRP INC,69347510

In [11]:
df.loc[[444,446], ["report_dt", "eff_dt"]]

      report_dt      eff_dt
444  2020/11/30  2021/01/08
446  2020/11/30  2021/01/08

In [12]:
df.loc[[444,446], "report_dt": "market_val"]

,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val
444,2020/11/30,17,2021/01/08,1.96,1542737.0,39154665.06
446,2020/11/30,19,2021/01/08,1.80,260036.0,35903170.52

In [13]:
df.iloc[[444,446], 2:5]

     security_rank      eff_dt  percent_tna
444             17  2021/01/08         1.96
446             19  2021/01/08         1.80

In [14]:
df.columns

Index(['portno', 'report_dt', 'security_rank', 'eff_dt', 'percent_tna',
       'nbr_shares', 'market_val', 'security_name', 'cusip'],
      dtype='object')

In [15]:
df.index

RangeIndex(start=0, stop=32878718, step=1)

In [16]:
df.dtypes

portno            object
report_dt         object
security_rank      int64
eff_dt            object
percent_tna      float64
nbr_shares       float64
market_val       float64
security_name     object
cusip             object
dtype: object

In [18]:
len(df["portno"].unique())

11920

In [20]:
df["percent_tna"].mean()

0.2945002086151897

In [21]:
df["percent_tna"].sum()

9682789.309999993

In [25]:
df["cusip"]

0           37045V10
1           19244610
2           61744644
3           71817210
4           22052L10
              ...
32878713    071734AH
32878714    071734AJ
32878715    071734AM
32878716    29273DAC
32878717    69318FAJ
Name: cusip, Length: 32878718, dtype: object

In [26]:
df["portno"].value_counts()

3066654    223027
3086928    185325
306841b    181445
3100110    127403
306920d    120721
            ...
3092553         1
3069210         1
3065319         1
3077046         1
3078942         1
Name: portno, Length: 11920, dtype: int64

In [27]:
df.describe()

       security_rank   percent_tna    nbr_shares    market_val
count   3.287872e+07  3.287872e+07  3.287872e+07  3.287872e+07
mean    1.077915e+03  2.945002e-01  4.154832e+07  8.366760e+06
std     1.793852e+03  1.651244e+00  8.185030e+09  1.376690e+08
min     1.000000e+00 -2.628000e+02 -1.188360e+13 -3.157247e+10
25%     1.310000e+02  1.000000e-02  8.000000e+03  9.254227e+04
50%     4.230000e+02  4.000000e-02  1.000000e+05  5.251210e+05
75%     1.228000e+03  1.900000e-01  8.250000e+05  2.523780e+06
max     1.866500e+04  3.822500e+02  9.665837e+12  7.359335e+10

In [28]:
filter_portno_306841b = df["portno"] == "306841b"
filter_portno_306841b

0           False
1           False
2           False
3           False
4           False
            ...
32878713    False
32878714    False
32878715    False
32878716    False
32878717    False
Name: portno, Length: 32878718, dtype: bool

In [29]:
df[filter_portno_306841b]

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
259610,306841b,2020/11/30,1387,2021/01/08,0.01,332200.0,4072772.00,Nov Inc ORD,62955J10
259611,306841b,2020/11/30,6776,2021/01/08,0.00,700000.0,654500.00,Nov Inc 3.95% 01-DEC-2042,637071AK
259612,306841b,2020/11/30,7951,2021/01/08,0.00,500000.0,506875.00,Nov Inc 3.6% 01-DEC-2029,637071AM
259613,306841b,2020/11/30,11367,2021/01/08,0.00,150000.0,160507.50,MORGAN STANLEY BK AMER MERRILL LYNCH TR 2014-C...,61690GAJ
259614,306841b,2020/11/30,11851,2021/01/08,0.00,30449.0,90433.53,HUNT COMPANIES FINANCE TRUST INC,44558T10
...,...,...,...,...,...,...,...,...,...
31986632,306841b,2021/11/30,15540,2021/12/21,0.00,9467.0,16283.24,U S WELL SERVICES INC,91274U20
31986633,306841b,2021/11/30,15540,2021/12/21,0.00,6688.0,9430.08,AVENUE THERAPEUTICS INC,05360L20
31986634,306841b,2021/11/30,15540,2021/12/21,0.00,9108.0,9869.90,Fannie Mae 01-JUN-2047 BH2088,3140GQKA
31986635,306841b,2021/11/30,15540,2021/12/21,0.00,250.0,154.23,AILERON THERAPEUTICS INC,00887A10
31986636,306841b,2021/11/30,15540,2021/12/21,0.00,2088.0,16056.72,CODA OCTOPUS GROUP INC,19188U20

In [30]:
df[filter_portno_306841b]["percent_tna"].sum()

1045.2900000000002

In [32]:
filter_eff_dt_20210108 = df["eff_dt"] == "2021/01/08"

In [33]:
df[filter_portno_306841b & filter_eff_dt_20210108]

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
259610,306841b,2020/11/30,1387,2021/01/08,0.01,332200.0,4072772.00,Nov Inc ORD,62955J10
259611,306841b,2020/11/30,6776,2021/01/08,0.00,700000.0,654500.00,Nov Inc 3.95% 01-DEC-2042,637071AK
259612,306841b,2020/11/30,7951,2021/01/08,0.00,500000.0,506875.00,Nov Inc 3.6% 01-DEC-2029,637071AM
259613,306841b,2020/11/30,11367,2021/01/08,0.00,150000.0,160507.50,MORGAN STANLEY BK AMER MERRILL LYNCH TR 2014-C...,61690GAJ
259614,306841b,2020/11/30,11851,2021/01/08,0.00,30449.0,90433.53,HUNT COMPANIES FINANCE TRUST INC,44558T10
259615,306841b,2020/11/30,12388,2021/01/08,0.00,19881.0,52088.22,GREAT ELM CAPITAL GROUP INC,39036P20
259616,306841b,2020/11/30,12388,2021/01/08,0.00,58455.0,61962.30,PROTEOSTASIS THERAPEUTICS INC,74373B10

In [35]:
filter_eff_dt_20210122 = df["eff_dt"] == "2021/01/22"
df[filter_portno_306841b & filter_eff_dt_20210122]["percent_tna"].sum()

82.50999999999999

In [36]:
df.groupby("portno").size()

portno
2998623    4155
2998638     929
2998809     862
2998821     629
2998923     420
           ...
315733b      16
315733e     363
3157347       5
315734a       3
3157350     428
Length: 11920, dtype: int64

In [39]:
df[df["portno"] == "2998623"].groupby("report_dt").sum()

C:\Users\Tibame_EX14\AppData\Local\Temp\ipykernel_2332\639061768.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df[df["portno"] == "2998623"].groupby("report_dt").sum()

            security_rank  percent_tna    nbr_shares    market_val
report_dt
2020/11/30          61888        99.79  3.817768e+09  1.213476e+10
2020/12/31          61544        99.76  3.894819e+09  1.232999e+10
2021/01/31          60135        99.77  3.936475e+09  1.203395e+10
2021/02/28          57735        99.80  3.980795e+09  1.257758e+10
2021/03/31          61166       100.01  4.637393e+09  1.290277e+10
2021/04/30          60465        99.96  4.606629e+09  1.325873e+10
2021/05/31          61501        99.97  4.503789e+09  1.339596e+10
2021/06/30          61534        99.78  4.673745e+09  1.324652e+10
2021/07/31          61189        99.88  4.569438e+09  1.314789e+10
2021/08/31          60836        99.76  4.612223e+09  1.323175e+10
2021/09/30          57369        99.89  4.630959e+09  1.294457e+10
2021/10/31          57387        99.90  4.652550e+09  1.335381e+10

In [40]:
df.groupby(["portno", "report_dt"]).sum()

C:\Users\Tibame_EX14\AppData\Local\Temp\ipykernel_2332\2110635014.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby(["portno", "report_dt"]).sum()

                    security_rank  percent_tna    nbr_shares    market_val
portno  report_dt
2998623 2020/11/30          61888        99.79  3.817768e+09  1.213476e+10
        2020/12/31          61544        99.76  3.894819e+09  1.232999e+10
        2021/01/31          60135        99.77  3.936475e+09  1.203395e+10
        2021/02/28          57735        99.80  3.980795e+09  1.257758e+10
        2021/03/31          61166       100.01  4.637393e+09  1.290277e+10
...                           ...          ...           ...           ...
315733b 2021/11/30            137        99.73  1.783122e+07  2.601732e+07
315733e 2021/11/30          66053       525.90  2.659001e+08  2.762602e+08
3157347 2021/11/30             19        55.06  6.300062e+06  6.299271e+06
315734a 2021/11/30              6       148.11  5.402436e+06  1.525456e+07
3157350 2021/11/30          92037        99.55  1.927648e+07  1.964126e+07

[99639 rows x 4 columns]

In [41]:
df.groupby(["portno", "report_dt"]).sum().head(30)

C:\Users\Tibame_EX14\AppData\Local\Temp\ipykernel_2332\824067948.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby(["portno", "report_dt"]).sum().head(30)

                    security_rank  percent_tna    nbr_shares    market_val
portno  report_dt
2998623 2020/11/30          61888        99.79  3.817768e+09  1.213476e+10
        2020/12/31          61544        99.76  3.894819e+09  1.232999e+10
        2021/01/31          60135        99.77  3.936475e+09  1.203395e+10
        2021/02/28          57735        99.80  3.980795e+09  1.257758e+10
        2021/03/31          61166       100.01  4.637393e+09  1.290277e+10
        2021/04/30          60465        99.96  4.606629e+09  1.325873e+10
        2021/05/31          61501        99.97  4.503789e+09  1.339596e+10
        2021/06/30          61534        99.78  4.673745e+09  1.324652e+10
        2021/07/31          61189        99.88  4.569438e+09  1.314789e+10
        2021/08/31          60836        99.76  4.612223e+09  1.323175e+10
        2021/09/30          57369        99.89  4.630959e+09  1.294457e+10
        2021/10/31          57387        99.90  4.652550e+09  1.335381e+10
2998638 2020/11/30           3021        99.89  4.856478e+08  8.460393e+09
        2020/12/31           3021        99.91  3.899337e+08  8.686967e+09
        2021/01/31           2847        99.95  3.413422e+08  8.490791e+09
        2021/02/28           2944        99.93  2.867240e+08  9.122478e+09
        2021/03/31           2934        99.96  2.719080e+08  9.583499e+09
        2021/04/30           3094        99.97  2.888745e+08  9.715914e+09
        2021/05/31           3017        99.94  2.969231e+08  1.006920e+10
        2021/06/30           3075        99.92  2.933560e+08  9.851654e+09
        2021/07/31           3254        99.91  2.893478e+08  9.714083e+09
        2021/08/31           3095        99.96  2.842540e+08  9.821117e+09
        2021/09/30           3095        99.87  2.492366e+08  9.549955e+09
        2021/10/31           3150        99.92  2.682409e+08  9.960822e+09
2998809 2020/11/30           2485        99.50  1.312320e+08  1.989293e+09
        2020/12/31           2485       100.14  1.542014e+08  2.141710e+09
        2021/01/31           2850        99.96  2.288131e+08  2.418156e+09
        2021/02/28           3240       102.10  3.811000e+08  3.143982e+09
        2021/03/31           3003       104.10  6.350974e+08  4.538543e+09
        2021/04/30           2926       101.15  6.666171e+08  5.097768e+09

In [42]:
df.columns

Index(['portno', 'report_dt', 'security_rank', 'eff_dt', 'percent_tna',
       'nbr_shares', 'market_val', 'security_name', 'cusip'],
      dtype='object')

In [43]:
print(len(df["security_name"].unique()))
print(len(df["cusip"].unique()))

707303
430883

In [46]:
df[df["security_name"] == ""]

Empty DataFrame
Columns: [portno, report_dt, security_rank, eff_dt, percent_tna, nbr_shares, market_val, security_name, cusip]
Index: []

In [48]:
df[df["cusip"].isna()]

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
66,2998623,2020/11/30,67,2021/01/08,0.60,60368000.0,72622704.00,Convertible Trust - Media FRN 04-Dec-2024,NaN
69,2998623,2020/11/30,70,2021/01/08,0.53,56758000.0,64023024.00,Convertible Trusthealthcare FRN 05-Feb-2024,NaN
74,2998623,2020/11/30,75,2021/01/08,0.51,60352000.0,61667673.60,Convertible Trust Healthcare FRN 19-Sep-2024,NaN
77,2998623,2020/11/30,78,2021/01/08,0.50,57077000.0,60741343.40,Convertible Trust - Consumer FRN 17-Jan-2024,NaN
85,2998623,2020/11/30,86,2021/01/08,0.41,-11964935.0,50395674.36,USD Cash,NaN
...,...,...,...,...,...,...,...,...,...
32877366,315724b,2021/11/30,48,2021/12/21,1.02,1280.0,84968.28,Bilibili Inc ORD,NaN
32877420,315724e,2021/11/30,52,2021/12/21,0.00,0.0,0.01,USD Cash,NaN
32877926,3157332,2021/11/30,506,2021/12/21,-0.05,-14062002.0,-14062002.02,Accounts Receivable & Payable,NaN
32878078,315733e,2021/11/30,152,2021/12/21,0.60,314144.0,314144.09,Cash and Cash Equivalents,NaN
32878291,3157350,2021/11/30,2,2021/12/21,1.76,348026.0,348025.83,USD Cash,NaN

In [50]:
df[df["security_name"].notna()]

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
0,2998623,2020/11/30,1,2021/01/08,2.55,7078982.0,3.103426e+08,GENERAL MOTORS CO,37045V10
1,2998623,2020/11/30,2,2021/01/08,1.98,3087680.0,2.412404e+08,COGNIZANT TECHNOLOGY SOLS CORP,19244610
2,2998623,2020/11/30,3,2021/01/08,1.89,3714760.0,2.296836e+08,MORGAN STANLEY DEAN WITTER & CO,61744644
3,2998623,2020/11/30,4,2021/01/08,1.75,2815186.0,2.132503e+08,PHILIP MORRIS INTERNATIONAL INC,71817210
4,2998623,2020/11/30,5,2021/01/08,1.65,5248941.0,2.011394e+08,CORTEVA INC,22052L10
...,...,...,...,...,...,...,...,...,...
32878713,3157350,2021/11/30,428,2021/12/21,0.11,25000.0,2.229475e+04,Bausch Health Companies Inc 5% 30-JAN-2028,071734AH
32878714,3157350,2021/11/30,429,2021/12/21,0.11,25000.0,2.148050e+04,Bausch Health Companies Inc 5.25% 30-JAN-2030,071734AJ
32878715,3157350,2021/11/30,429,2021/12/21,0.11,25000.0,2.148400e+04,Bausch Health Companies Inc 5% 15-FEB-2029,071734AM
32878716,3157350,2021/11/30,431,2021/12/21,0.10,25000.0,1.918738e+04,Endo DAC 6% 30-JUN-2028,29273DAC
32878717,3157350,2021/11/30,432,2021/12/21,0.08,25000.0,1.497188e+04,PBF Holding Company LLC 6% 15-FEB-2028,69318FAJ

In [54]:
print(
    len(df[df["cusip"].notna()]["security_name"].unique())
)
print(
    len(df[df["cusip"].notna()]["cusip"].unique())
)

629503
430882